export function formatCurrency(value, currency = 'USD') {
  const symbols = {
    USD: '$',
    CAD: 'CA$',
    AUD: 'AU$',
    GBP: '£',
    EUR: '€',
    BDT: '৳',
    BRL: 'R$',
    BGN: 'лв',
    CLP: 'CL$',
    CNY: '¥',
    COP: 'CO$',
    HRK: 'kn',
    CZK: 'Kč',
    DKK: 'kr',
    AED: 'د.إ',
    GEL: '₾',
    HKD: 'HK$',
    HUF: 'Ft',
    INR: '₹',
    IDR: 'Rp',
    ILS: '₪',
    JPY: '¥',
    KES: 'Ksh',
    MYR: 'RM',
    MXN: 'MX$',
    MAD: 'د.م.',
    NZD: 'NZ$',
    NGN: '₦',
    NOK: 'kr',
    PKR: 'Rs',
    PEN: 'S/.',
    PHP: '₱',
    PLN: 'zł',
    RON: 'Lei',
    RUB: '₽',
    RWF: 'FRw',
    SGD: 'S$',
    ZAR: 'R',
    KRW: '₩',
    LKR: 'Rs',
    SEK: 'kr',
    CHF: 'CHF',
    THB: '฿',
    TRY: '₺',
    UGX: 'Ush',
    UAH: '₴',
    VND: '₫',
    ZMW: 'ZK',
    ZWL: 'ZWL$'
    };


  const symbol = symbols[currency] || '$';
  return `${symbol}${Math.round(value).toLocaleString()}`;
}
